#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb  8 13:30:23 2018

@author: spiffkringle
"""
import numpy as np
from pylab import plot

p = 0.5
q = 0.5
a = 2.0

vals = []

for i in range(20):
    n = i +1
    val = (n*p*q)/(a*n*p*(n*p*q)**(1/2))
    print(val)
    vals.append(val)
    
plot(vals)

def EstSigma(vec):
    mean = sum(vec)/len(vec)
    std = (1/(len(vec)-1) * sum([(i - mean)**2 for i in vec]))**(1/2)
    return std

def EstVar(vec):
    mean = sum(vec)/len(vec)
    std = (1/(len(vec)-1) * sum([(i - mean)**2 for i in vec]))
    return std

Pvec = np.array([0.001,0.009,0.009,0.009,0.081,0.081,0.081,0.729])
Xbar = np.array([0,1/3,1/3,1/3,2/3,2/3,2/3,1])
S1 = np.array([0,0,0,0,1,1,1,1])
s2 = np.array([0,0.5,0.5,0.5,0.5,0.5,0.5,1])

np.random.random()

