#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 15 13:35:22 2018

@author: spiffkringle
"""

import numpy as np

def CosTheta(v1,v2):
    """
    Returns the cosine similarity between two vectors v1 and v2 which are given
    as lists or np arrays
    """
    v1 = np.array(v1)
    v2 = np. array(v2)
    return np.dot(v1,v2)/(((np.dot(v1,v1))**(1/2))*((np.dot(v2,v2))**(1/2)))

x= CosTheta([1,0,-1],[0,1,-1])

print(np.arccos(x)*57.2958)